# SPDX-FileCopyrightText: 2025 Tilman Griesel
#
# SPDX-License-Identifier: GPL-3.0-or-later AND LicenseRef-AlpineZen-Trademark

name: Release Job

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux]
        arch: [arm64, amd64]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set default version
        run: echo "VERSION=dev" >> $GITHUB_ENV

      - name: Get version from tag
        if: startsWith(github.ref, 'refs/tags/')
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Get build number
        id: get_build_number
        run: echo "BUILD_NUMBER=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Debug Information
        run: |
          echo "Release tag: ${{ github.ref }}"
          echo "Workflow name: ${{ github.workflow }}"
          echo "Job name: ${{ github.job }}"
          echo "Repository: ${{ github.repository }}"
          echo "Commit: ${{ github.sha }}"
          echo "Version: ${{ env.VERSION }}"
          echo "Build Number: ${{ env.BUILD_NUMBER }}"

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: .

      - name: Prepare environment for nfpm
        run: |
          mkdir -p ./dist
          for arch in arm64 amd64; do
            if [ -d "./alpinezen-wallpaper-linux-$arch" ]; then
              # Extract the tar.gz into the directory for nfpm to access
              mkdir -p ./dist/linux-$arch
              tar -xzf ./alpinezen-wallpaper-linux-$arch.tar.gz/alpinezen-wallpaper-linux-$arch.tar.gz -C ./dist/linux-$arch
            fi
          done
          # Replace version in nfpm.yaml
          sed -i "s/version: \".*\"/version: \"${{ env.VERSION }}\"/" assets/linux/nfpm.yaml

      - name: Create Linux deb
        uses: burningalchemist/action-gh-nfpm@v1
        if: matrix.os == 'linux'
        with:
          packager: deb
          config: assets/linux/nfpm.yaml
          target: alpinezen-wallpaper-${{ matrix.os }}-${{ matrix.arch }}.deb

      - name: Create Linux rpm
        uses: burningalchemist/action-gh-nfpm@v1
        if: matrix.os == 'linux'
        with:
          packager: rpm
          config: assets/linux/nfpm.yaml
          target: alpinezen-wallpaper-${{ matrix.os }}-${{ matrix.arch }}.rpm

      - name: Rename artifacts with version and build number
        run: |
          find . -type f \( -name "*.tar.gz" -o -name "*.dmg" \) | while read file; do
            dir=$(dirname "$file")
            base=$(basename "$file")

            if [[ "$base" =~ \.tar\.gz$ ]]; then
              name="${base%.tar.gz}"
              new_name="${name}-${VERSION}.tar.gz"
            else
              name="${base%.*}"
              ext="${base##*.}"
              new_name="${name}-${VERSION}.${ext}"
            fi

            mv "$file" "$dir/$new_name"
          done

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.token }}
          artifacts: "**/*.tar.gz,**/*.dmg,**/*.deb,**/*.rpm"
