# SPDX-FileCopyrightText: 2025 Tilman Griesel
#
# SPDX-License-Identifier: GPL-3.0-or-later AND LicenseRef-AlpineZen-Trademark

name: VulnCheck

on:
  workflow_call:
  pull_request:
    branches:
      - "main"

  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  vulncheck:
    name: Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.0
      - name: Get official govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
        shell: bash
      - name: Run govulncheck
        run: govulncheck -show verbose ./...
        shell: bash
